### ISSUE TITLE
Cannot upload SD

### ISSUE THREAD

**Issue by tpcolson** [khibma/update-hosted-feature-service#5]
For a MXD from which a service can be successfully overwritten when publishing from ArcMap, the same service cannot be updated using update.py with the following error:

Starting Feature Service publish process
found Feature Service : f4c43de7a4964371b1fbba68eaa15cfb
found Service Definition : d4333434f3c34a75b14b5d42fe811345
Created X:\GIS_Final\data\basedata\basemap\Data\Working\Python_Automated_Scripts\UPDATE_AGOL\tempDir\GRSM_TRAIL_INVENTORY.sd

Traceback (most recent call last):
File "X:\GIS_Final\data\basedata\basemap\Data\Working\Python_Automated_Scripts\UPDATE_AGOL\update.py", line 309, in 
if upload(finalSD, tags, description):
File "X:\GIS_Final\data\basedata\basemap\Data\Working\Python_Automated_Scripts\UPDATE_AGOL\update.py", line 171, in upload
response = requests.post(url, files=filesUp);
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\api.py", line 109, in post
return request('post', url, data=data, json=json, *kwargs)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\api.py", line 50, in request
response = session.request(method=method, url=url, *kwargs)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\sessions.py", line 451, in request
prep = self.prepare_request(req)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\sessions.py", line 382, in prepare_request
hooks=merge_hooks(request.hooks, self.hooks),
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\models.py", line 296, in prepare
self.prepare_body(data, files, json)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\models.py", line 444, in prepare_body
(body, content_type) = self._encode_files(files, data)
File "C:\Python27\ArcGIS10.2\Lib\site-packages\requests\models.py", line 150, in _encode_files
fdata = fp.read()
MemoryError

**Comment by tpcolson** [comment]
Interesting, I tested this with ANOTHER FS, and it worked, and have discovered there is a SD-size limit, which I think is a requests issue: the SD I was trying it with is 500+ mb (Photo attachments). Wonder if there's a way to find out what the SD size limit is?

**Comment by khibma** [comment]
If you're still having this issue and are in a position to test it, could you please download the latest version from here (https://github.com/khibma/update-hosted-feature-service) and attempt to publish. I believe the changes to the internal upload mechanism should support your workflow. If its good I'll sync these changes with the arcpy account.

**Comment by khibma** [comment]
fixed with pr#11
